# App Engine deployment configuration
# GCP Project: marketsphere-476701

runtime: nodejs20

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /.*
    script: auto
    secure: always
