# Google Cloud Build configuration for DFP Connect
# Project ID: marketsphere-476701

steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # Build the Next.js application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/marketsphere-476701/dfp-connect:$SHORT_SHA'
      - '-t'
      - 'gcr.io/marketsphere-476701/dfp-connect:latest'
      - '.'

  # Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/marketsphere-476701/dfp-connect:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dfp-connect'
      - '--image'
      - 'gcr.io/marketsphere-476701/dfp-connect:$SHORT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

# Store images in Google Container Registry
images:
  - 'gcr.io/marketsphere-476701/dfp-connect:$SHORT_SHA'
  - 'gcr.io/marketsphere-476701/dfp-connect:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1800s'
