import type { TimelineEvent } from '@/lib/types/timeline'

/**
 * 장애와가족플랫폼 연혁 (2018-2024)
 */
export const timelineEvents: TimelineEvent[] = [
  {
    year: '2018',
    month: '03',
    title: '장애와가족플랫폼 사회적협동조합 설립',
    description: '장애인 가족의 삶의 질 향상을 위한 사회적 돌봄체계 구축을 목표로 출범',
    isMajor: true,
    category: 'founding',
  },
  {
    year: '2018',
    month: '06',
    title: '긴급돌봄 서비스 시작',
    description: '24시간 긴급돌봄 서비스 제공 시작, 첫 해 50가구 지원',
    category: 'service',
  },
  {
    year: '2019',
    month: '02',
    title: '서울시 사회적경제 인증',
    description: '서울시로부터 사회적경제기업 인증 획득',
    category: 'achievement',
  },
  {
    year: '2019',
    month: '09',
    title: '방과후 홈티 프로그램 개시',
    description: '장애 아동을 위한 맞춤형 교육 프로그램 시작',
    isMajor: true,
    category: 'service',
  },
  {
    year: '2020',
    month: '03',
    title: '코로나19 긴급 대응 체계 구축',
    description: '비대면 상담 및 긴급돌봄 확대 운영',
    category: 'service',
  },
  {
    year: '2020',
    month: '11',
    title: '100가구 지원 달성',
    description: '누적 서비스 제공 가구 100가구 돌파',
    category: 'achievement',
  },
  {
    year: '2021',
    month: '04',
    title: '가족 상담 센터 개소',
    description: '전문 상담사를 통한 개별/가족 상담 서비스 정식 오픈',
    isMajor: true,
    category: 'expansion',
  },
  {
    year: '2021',
    month: '08',
    title: '기업 파트너십 10개 체결',
    description: 'B2B 전문인력 파견 서비스 확대',
    category: 'partnership',
  },
  {
    year: '2022',
    month: '01',
    title: '맞춤형 여행 프로그램 론칭',
    description: '장애인 가족을 위한 안전한 여행 설계 및 동행 서비스 시작',
    category: 'service',
  },
  {
    year: '2022',
    month: '06',
    title: '300가구 지원 달성',
    description: '누적 서비스 제공 가구 300가구 돌파',
    isMajor: true,
    category: 'achievement',
  },
  {
    year: '2022',
    month: '11',
    title: '고용노동부 우수 사회적기업 선정',
    description: '사회적 가치 창출 및 일자리 창출 공로 인정',
    category: 'achievement',
  },
  {
    year: '2023',
    month: '03',
    title: '디지털 플랫폼 구축 착수',
    description: 'DFP Connect 웹 플랫폼 개발 시작',
    category: 'expansion',
  },
  {
    year: '2023',
    month: '07',
    title: '협력 기관 30개 돌파',
    description: '전국 복지센터, 학교, 기업과의 파트너십 확대',
    category: 'partnership',
  },
  {
    year: '2023',
    month: '12',
    title: '500가구 지원 달성',
    description: '누적 서비스 제공 가구 500가구 돌파',
    isMajor: true,
    category: 'achievement',
  },
  {
    year: '2024',
    month: '03',
    title: '창립 6주년',
    description: '6년간 500가구 지원, 45개 협력 파트너십, 15억원 사회적 가치 창출',
    isMajor: true,
    category: 'achievement',
  },
  {
    year: '2024',
    month: '09',
    title: 'DFP Connect 플랫폼 정식 오픈',
    description: '온라인 서비스 신청 및 커뮤니티 기능 제공 시작',
    isMajor: true,
    category: 'expansion',
  },
]
